# Generated by Django 3.2.3 on 2021-05-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('created_at', models.CharField(max_length=50)),
                ('updated_at', models.CharField(max_length=50)),
            ],
        ),
    ]
